#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Install Google repo.
  get_url:
    url: "{{ repo_url }}"
    dest: "{{ repo_dir }}"
    mode: 0755

- name: add repo_dir to path
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: 'PATH='
    line: 'PATH=/bin:/usr/bin:/usr/local/bin'
  when: ansible_distribution == 'NA'

